# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('telefone', models.CharField(max_length=11)),
                ('rua', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
            ],
        ),
    ]
