# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='imagem',
            field=models.ImageField(default='None', upload_to='aluguel/'),
        ),
    ]
